/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, forwardRef, useImperativeHandle, useState, memo } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import Flag from "./Flag";

export const Box = memo(
    forwardRef((props, ref) => {
        const group = useRef();
        const { nodes, materials, animations } = useGLTF("/mailbox.glb");
        const { actions } = useAnimations(animations, group);
        const [isFlagUp, setIsFlagUp] = useState(false);

        useImperativeHandle(ref, () => ({
            toggleFlag: () => {
                setIsFlagUp((prev) => !prev);
            },
            playAnimation: (animationName, reverse = false) => {
                // Stop all current animations
                Object.values(actions).forEach((action) => {
                    if (action) {
                        action.stop();
                    }
                });

                if (actions[animationName]) {
                    const action = actions[animationName];
                    action.reset();
                    action.setLoop(2200, 1); // LoopOnce = 2200, play only 1 time
                    action.clampWhenFinished = true;

                    if (reverse) {
                        action.time = action.getClip().duration;
                        action.timeScale = -1;
                    } else {
                        action.timeScale = 1;
                    }

                    action.fadeIn(0.1).play();
                }
            },
            playAnimationWithoutStopping: (animationName, reverse = false) => {
                if (actions[animationName]) {
                    const action = actions[animationName];
                    action.reset();
                    action.setLoop(2200, 1); // LoopOnce = 2200, play only 1 time
                    action.clampWhenFinished = true;

                    if (reverse) {
                        action.time = action.getClip().duration;
                        action.timeScale = -1;
                    } else {
                        action.timeScale = 1;
                    }

                    action.fadeIn(0.1).play();
                }
            },
            getAvailableAnimations: () => {
                return Object.keys(actions).filter(
                    (key) => actions[key] !== undefined
                );
            },
        }));

        return (
            <group ref={group} {...props} dispose={null}>
                <group name="Scene">
                    <group name="Mailbox001" position={[0.001, 1.954, 0.001]}>
                        <mesh
                            name="Address_Bolts001"
                            castShadow
                            receiveShadow
                            geometry={nodes.Address_Bolts001.geometry}
                            material={materials["Bolts SF"]}
                            position={[0.035, -0.273, -0.171]}
                            rotation={[0, 0, -Math.PI / 2]}
                        />
                        <mesh
                            name="Address001"
                            castShadow
                            receiveShadow
                            geometry={nodes.Address001.geometry}
                            material={materials["Address SF"]}
                            position={[0.034, -0.366, -0.187]}
                            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        />
                        <mesh
                            name="Angled_Beam_Bolts001"
                            castShadow
                            receiveShadow
                            geometry={nodes.Angled_Beam_Bolts001.geometry}
                            material={materials["Bolts SF"]}
                            position={[-0.019, -0.592, 0.073]}
                            rotation={[2.356, -Math.PI / 2, 0]}
                        />
                        <mesh
                            name="Angled_Beam003"
                            castShadow
                            receiveShadow
                            geometry={nodes.Angled_Beam003.geometry}
                            material={materials["Beam SF"]}
                            position={[0, -0.649, -0.028]}
                            rotation={[Math.PI / 4, 0, 0]}
                        />
                        <mesh
                            name="Base_Bolts001"
                            castShadow
                            receiveShadow
                            geometry={nodes.Base_Bolts001.geometry}
                            material={materials["Bolts SF"]}
                            position={[0.087, -0.504, 0.285]}
                            rotation={[0, 0, -1.396]}
                        />
                        <mesh
                            name="Base003"
                            castShadow
                            receiveShadow
                            geometry={nodes.Base003.geometry}
                            material={materials["Base SF"]}
                            position={[0, -0.409, 0.102]}
                        />
                        <mesh
                            name="Door001"
                            castShadow
                            receiveShadow
                            geometry={nodes.Door001.geometry}
                            material={materials["Base SF"]}
                            position={[0, -0.499, 0.327]}
                            rotation={[1.564, 0, 0]}
                        >
                            <mesh
                                name="Door_Hinge003"
                                castShadow
                                receiveShadow
                                geometry={nodes.Door_Hinge003.geometry}
                                material={materials["Base SF"]}
                                position={[0.091, 0, 0.009]}
                                rotation={[0, 0, -Math.PI / 2]}
                            />
                            <mesh
                                name="Door_Tab003"
                                castShadow
                                receiveShadow
                                geometry={nodes.Door_Tab003.geometry}
                                material={materials["Base SF"]}
                                position={[0, 0.19, 0.046]}
                                rotation={[Math.PI / 2, 0, 0]}
                            >
                                <mesh
                                    name="Door_Tab_Bolts001"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Door_Tab_Bolts001.geometry}
                                    material={materials["Base SF"]}
                                    position={[0, -0.002, 0.011]}
                                    rotation={[0, -1.571, 0]}
                                />
                            </mesh>
                        </mesh>
                        <mesh
                            name="Flag_Hinge_2003"
                            castShadow
                            receiveShadow
                            geometry={nodes.Flag_Hinge_2003.geometry}
                            material={materials["Flag SF"]}
                            position={[0.081, -0.401, 0.273]}
                            rotation={[0, 0, -Math.PI / 2]}
                        />
                        <mesh
                            name="Flag_Hinge_3003"
                            castShadow
                            receiveShadow
                            geometry={nodes.Flag_Hinge_3003.geometry}
                            material={materials["Flag SF"]}
                            position={[0.081, -0.409, 0.262]}
                            rotation={[0, 0, -Math.PI / 2]}
                        />
                        <mesh
                            name="Flag_Hinge003"
                            castShadow
                            receiveShadow
                            geometry={nodes.Flag_Hinge003.geometry}
                            material={materials["Flag SF"]}
                            position={[0.092, -0.401, 0.273]}
                            rotation={[0, 0, -Math.PI / 2]}
                        />
                        <Flag
                            isUp={isFlagUp}
                            geometry={nodes.Flag003.geometry}
                            material={materials["Flag SF"]}
                        />
                        <mesh
                            name="Horizontal_Beam_Bolts001"
                            castShadow
                            receiveShadow
                            geometry={nodes.Horizontal_Beam_Bolts001.geometry}
                            material={materials["Bolts SF"]}
                            position={[0.031, -0.563, -0.191]}
                            rotation={[0, 0, -Math.PI / 2]}
                        />
                        <mesh
                            name="Horizontal_Beam003"
                            castShadow
                            receiveShadow
                            geometry={nodes.Horizontal_Beam003.geometry}
                            material={materials["Beam SF"]}
                            position={[0, -0.547, -0.002]}
                            rotation={[Math.PI / 2, 0, 0]}
                        />
                        <mesh
                            name="Inner_Plate_Beam003"
                            castShadow
                            receiveShadow
                            geometry={nodes.Inner_Plate_Beam003.geometry}
                            material={materials["Beam SF"]}
                            position={[0, -0.5, 0.102]}
                        />
                        <mesh
                            name="Inner_Plate003"
                            castShadow
                            receiveShadow
                            geometry={nodes.Inner_Plate003.geometry}
                            material={materials["Bolts SF"]}
                            position={[0, -0.501, 0.133]}
                        />
                        <mesh
                            name="Mail001"
                            castShadow
                            receiveShadow
                            geometry={nodes.Mail001.geometry}
                            material={materials["Material.005"]}
                            position={[-0.001, -0.43, 0.202]}
                            rotation={[Math.PI / 2, 0.197, -Math.PI / 2]}
                        />
                        <mesh
                            name="Reflective_1_Bolts001"
                            castShadow
                            receiveShadow
                            geometry={nodes.Reflective_1_Bolts001.geometry}
                            material={materials["Bolts SF"]}
                            position={[0.032, -0.691, -0.186]}
                            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        />
                        <mesh
                            name="Reflective_1_Bolts003"
                            castShadow
                            receiveShadow
                            geometry={nodes.Reflective_1_Bolts003.geometry}
                            material={materials["Bolts SF"]}
                            position={[0.032, -1.107, -0.186]}
                            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        />
                        <group
                            name="Reflective_1005"
                            position={[0.032, -0.691, -0.186]}
                            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        >
                            <mesh
                                name="Plane056"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane056.geometry}
                                material={materials["Reflective SF"]}
                            />
                            <mesh
                                name="Plane056_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane056_1.geometry}
                                material={materials["Reflective 1 SF"]}
                            />
                        </group>
                        <group
                            name="Reflective_1006"
                            position={[0.032, -1.107, -0.186]}
                            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        >
                            <mesh
                                name="Plane064"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane064.geometry}
                                material={materials["Reflective SF"]}
                            />
                            <mesh
                                name="Plane064_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane064_1.geometry}
                                material={materials["Reflective 1 SF"]}
                            />
                        </group>
                        <mesh
                            name="Relfective_2_Bolts001"
                            castShadow
                            receiveShadow
                            geometry={nodes.Relfective_2_Bolts001.geometry}
                            material={materials["Bolts SF"]}
                            position={[0.033, -0.948, -0.186]}
                            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        />
                        <group
                            name="Relfective_2003"
                            position={[0.033, -0.948, -0.186]}
                            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        >
                            <mesh
                                name="Circle007"
                                castShadow
                                receiveShadow
                                geometry={nodes.Circle007.geometry}
                                material={materials.Reflective}
                            />
                            <mesh
                                name="Circle007_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Circle007_1.geometry}
                                material={materials["Material.006"]}
                            />
                        </group>
                        <mesh
                            name="Vertical_Beam003"
                            castShadow
                            receiveShadow
                            geometry={nodes.Vertical_Beam003.geometry}
                            material={materials["Beam SF"]}
                            position={[0, -0.936, -0.186]}
                        />
                    </group>
                </group>
            </group>
        );
    })
);

useGLTF.preload("/mailbox2.glb");
